### ISSUE TITLE
能支持【加急处理投票】吗？

### ISSUE THREAD

**Issue by wenbo1039** [JCCDex/jcc-moac-multisig-wallet#16]
申请人可以加钱（moac）让自己的投票被加急处理吗？
不是要去买通投票人，而是可以加一个叮一下别的投票人的功能吗？就是我加钱，然后你把我申请成为投票人的消息推送给有权投票的人。提高时效性。
这个功能能做吗？

**Comment by GinMu** [comment]
不支持
