### ISSUE TITLE
提案明细

### ISSUE THREAD

**Issue by tigerblock** [JCCDex/jcc-moac-multisig-wallet#24]
提案明细显示的是 moac地址申请成为投票人，其他的投票人其实不知道这个moac地址后面对应的人，那么赞成或者反对都没有实质的意义，有可能 有申请的都会成为投票人，那么投票人是否会太多？智能合约信任能否独立与 人的信任？

**Comment by GinMu** [comment]
不是操作问题或程序bug, 不在此issue范围内
