### ISSUE TITLE
顶部导航最好跟钱包背景色一致

### ISSUE THREAD

**Issue by apencil** [JCCDex/jcc-moac-multisig-wallet#3]
![image](https://user-images.githubusercontent.com/6964799/66545957-67af9180-eb6e-11e9-8df2-6169a416b0ef.png)

![image](https://user-images.githubusercontent.com/6964799/66545920-58304880-eb6e-11e9-83a4-2d3068c19a08.png)

**Comment by VVanaheim** [comment]
优盾的钱包界面就简洁大气
